Update scheduled_wf.yml

diff --git a/.github/workflows/scheduled_wf.yml b/.github/workflows/scheduled_wf.yml
--- a/.github/workflows/scheduled_wf.yml
+++ b/.github/workflows/scheduled_wf.yml
@@ -9,16 +9,33 @@ jobs:
     runs-on: ubuntu-20.04
     steps:
       - uses: actions/checkout@v2
+      
       - name: Set up Python
-        uses: actions/setup-python@master
+        uses: actions/setup-python@v2
         with:
           python-version: 3.8
-          max_attempts: 3
-          retry_on: error
+
       - name: Setup Env
         run: |
-          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
-          python exec_map.py
+          retries=3
+          until_failure=0
+          while [ $retries -gt 0 ]; do
+            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+            python exec_map.py
+            if [ $? -eq 0 ]; then
+              until_failure=0
+              break
+            else
+              retries=$((retries - 1))
+              until_failure=$((until_failure + 1))
+              sleep 10 # Add a delay between retries 
+            fi
+          done
+          if [ $until_failure -gt 0 ]; then
+            echo "Failed after $until_failure attempts."
+            exit 1
+          fi
+
       - name: Git_Upload
         run: |
           git config --global user.email "michael-94@windowslive.com"
